In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris['Class'] = load_iris().target
iris['Class'] = iris['Class'].map({0:'Setosa',
                                    1:'Versicolour',
                                    2:'Virginica'})

In [2]:
iris_dummy = pd.get_dummies(iris, columns=['Class'])
iris_dummy

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Class_Setosa,Class_Versicolour,Class_Virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [3]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris['Class'] = load_iris().target
iris['Class'] = iris['Class'].map({0:'Setosa',
                                    1:'Versicolour',
                                    2:'Virginica'})

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.drop(columns='Class'),
                                                     iris['Class'], 
                                                     test_size=0.2,
                                                     random_state=1004
)
print('X_train :', X_train.shape, 'X_test :', X_test.shape)
print('y_train :', y_train.shape, 'y_test: ', y_test.shape)

X_train : (120, 4) X_test : (30, 4)
y_train : (120,) y_test:  (30,)

In [5]:
X_train.head(3)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
87                 6.3               2.3                4.4               1.3
67                 5.8               2.7                4.1               1.0
131                7.9               3.8                6.4               2.0

In [6]:
y_train.head(3)

87     Versicolour
67     Versicolour
131      Virginica
Name: Class, dtype: object

In [7]:
iris['Class'].value_counts()

Class
Setosa         50
Versicolour    50
Virginica      50
Name: count, dtype: int64

In [8]:
y_train.value_counts()

Class
Versicolour    41
Setosa         40
Virginica      39
Name: count, dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split(iris.drop(columns='Class'),
                                                     iris['Class'], 
                                                     test_size=0.2,
                                                     stratify=iris['Class'])
print('X_train :', X_train.shape, '\tX_test :', X_test.shape)
print('y_train :', y_train.shape, '\ty_test :', y_test.shape)

X_train : (120, 4) 	X_test : (30, 4)
y_train : (120,) 	y_test : (30,)

In [10]:
y_train.value_counts()

Class
Versicolour    40
Virginica      40
Setosa         40
Name: count, dtype: int64

In [11]:
'''
StandardScaler
- 기본 스케일링 방식으로 평균이 0, 분산이 1인 정규분포로 스케일링한다.
- 최솟값과 최댓값의 크기를 제한하지않아 이상치에 매우 민감하다.
- 이상치를 미리 확인 및 정제한 후 사용하는 것이 좋다.
- 회귀보다는 분류분석에서 유용하다.
'''
from sklearn.preprocessing import StandardScaler
StdScaler = StandardScaler()

StdScaler.fit(X_train)
X_train_sc = StdScaler.transform(X_train)

X_test_sc = StdScaler.transform(X_test)

print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_train_sc.min(),
                                               X_train_sc.max(),
                                               X_train_sc.mean(),
                                               X_train_sc.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_test_sc.min(),
                                               X_test_sc.max(),
                                               X_test_sc.mean(),
                                               X_test_sc.std()))

		(min, max) (mean, std)
Train_scaled (-2.37, 3.06) (0.00, 1.00)
Test_scaled (-1.92, 2.52) (0.04, 0.98)

In [12]:
''' 
MinMaxScaler
- 컬럼들을 0과 1사이의 값으로 스케일링 하는 방식
- 최솟값이 0, 최댓값이 1이다.
- 이상치에 매우 민감하므로 이상치를 미리 정제한 후 수행하는 것이 좋다.
- 분류보다는 회귀에 유용한 방식이다.
'''
from sklearn.preprocessing import MinMaxScaler

MmScaler = MinMaxScaler()

MmScaler.fit(X_train)
X_train_sc = MmScaler.transform(X_train)

X_test_sc = MmScaler.transform(X_test)

print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_train_sc.min(),
                                               X_train_sc.max(),
                                               X_train_sc.mean(),
                                               X_train_sc.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_test_sc.min(),
                                               X_test_sc.max(),
                                               X_test_sc.mean(),
                                               X_test_sc.std()))

		(min, max) (mean, std)
Train_scaled (0.00, 1.00) (0.45, 0.27)
Test_scaled (-0.03, 1.06) (0.46, 0.27)

In [13]:
'''
Max Abs Scaler 
- 최대절댓값과 0이 각각 1,0이 되도록 스케일링 하는 정규화 방식
- 모든 값을 -1과 1사이로 표현한다.
- 데이터가 양수인 경우 MinMaxScaler와 동일하다.
- 이상치에 매우 민감하다.
- 분류보다는 회귀분석에 유용하다.
''' 

from sklearn.preprocessing import MaxAbsScaler
MaScaler = MaxAbsScaler()

MaScaler.fit(X_train)
X_train_sc = MaScaler.transform(X_train)

X_test_sc = MaScaler.transform(X_test)

print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_train_sc.min(),
                                               X_train_sc.max(),
                                               X_train_sc.mean(),
                                               X_train_sc.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_test_sc.min(),
                                               X_test_sc.max(),
                                               X_test_sc.mean(),
                                               X_test_sc.std()))

		(min, max) (mean, std)
Train_scaled (0.04, 1.00) (0.62, 0.24)
Test_scaled (0.04, 1.03) (0.62, 0.24)

In [14]:
'''
Robust Scaler
- 평균과 분산 대신 중앙값(Median)과 사분위 값을 활용하는 방식이다
- 중앙값을 0으로 설정하고 IQR을 사용하여 이상치의 영향을 최소화한다.
- quantile_range 파라미터
  : default 값: [0.25, 0.75]를 조정하여
    더 넓거나 좁은 범위의 값을 이상치로 설정하여 정제할 수 있다.
'''
from sklearn.preprocessing import RobustScaler
RuScaler = RobustScaler()

RuScaler.fit(X_train)
X_train_sc = RuScaler.transform(X_train)

X_Test_sc = RuScaler.transform(X_test)

print("\t\t(min, max) (mean, std)")
print("Train_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_train_sc.min(),
                                               X_train_sc.max(),
                                               X_train_sc.mean(),
                                               X_train_sc.std()))
print("Test_scaled (%.2f, %.2f) (%.2f, %.2f)"%(X_test_sc.min(),
                                               X_test_sc.max(),
                                               X_test_sc.mean(),
                                               X_test_sc.std()))

		(min, max) (mean, std)
Train_scaled (-2.00, 2.80) (-0.03, 0.66)
Test_scaled (0.04, 1.03) (0.62, 0.24)